import { useState, useEffect } from 'react';
import styles from "@/styles/Home.module.css";
import Head from "next/head";
import SpinnerInsumo from '@/components/atoms/SpinnerInsumo';
import CrudApp from '@/components/templates/CrudApp';

export default function Home() {
  const [isLoading, setIsLoading] = useState(true);

  useEffect(() => {
    const timer = setTimeout(() => {
      setIsLoading(false);
    }, 5000);

    return () => clearTimeout(timer);
  }, [])

  return (
      <>
      <Head>
        <title>Inventario de Turno</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/nurshing.ico" />
      </Head>
      {isLoading ? (
        <SpinnerInsumo/> 
      ) : (
        <>
        <div className={styles.fade}>
        <CrudApp/>
        </div>
        </>
      )}
      </>
  );
}
