import { useState, useEffect } from 'react';
import Head from "next/head";
import SpinnerInsumo from '@/components/atoms/SpinnerInsumo';

export default function Home() {
  const [isLoading, setIsLoading] = useState(true);

  useEffect(() => {
    const timer = setTimeout(() => {
      setIsLoading(false);
    }, 2000);

    return () => clearTimeout(timer);
  }, [])

  return (
    <>
    <div>
      <>
      <Head>
        <title>Inventario de Turno</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/react.png" />
      </Head>

      <SpinnerInsumo/>
    
      </>
    </div>
    </>
  );
}
