
import CrudApp from "@/components/templates/CrudApp";
import Head from "next/head";

export default function Home() {
  return (
    <>
      <Head>
        <title>Inventario de Turno</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/react.png" />
      </Head>

      <CrudApp/>
    </>
  );
}
